### ISSUE TITLE
First run crash

### ISSUE THREAD

**Issue by florianpircher** [HugoJourdan/Rainbow-FontView#1]
Continuing from https://github.com/schriftgestalt/glyphs-packages/pull/125#issuecomment-1438519242

> ```python
> if not f"{GSGlyphsInfo.applicationSupportPath()}/info":
> 	os.makedirs(f"{GSGlyphsInfo.applicationSupportPath()}/info")
> ```
>
> applicationSupportPath alway exist, but not "info" folder, that's what I'm checking here.

But you are not checking whether the info folder exists, you are checking whether the _string representing path of the info folder_ exists. And the string always exists, whether the folder does not not.

**Comment by HugoJourdan** [comment]
I got it, sorry Florian.
It's correctly fixed now.
