### ISSUE TITLE
Warning about layer color when in glyph color mode

### ISSUE THREAD

**Issue by florianpircher** [HugoJourdan/Rainbow-FontView#2]
When switching to glyph color mode like so:

```python
Glyphs.font.userData["hugojourdan.RainbowFontView.labelUsed"] = "Glyph"
```

I get this warning when activating Rainbow FontView in a font without layer colors but with glyph colors:

<img width="409" alt="Bildschirm­foto 2023-02-21 um 15 41 49" src="https://user-images.githubusercontent.com/3776198/220375673-4a1e48b4-efbc-4afa-ba3a-4bf4ccd48cc4.png">

The title talks about layer color but the message body talks about glyph color. Also, the Option key is not needed for glyph colors. But, the plugin does work in sorting the Font View by color.

**Comment by HugoJourdan** [comment]
Thanks Florian for this report.
Now, warning message depend of labeUsed set.
