### ISSUE TITLE
Plugin crashes when the info folder does not exist

### ISSUE THREAD

**Issue by florianpircher** [HugoJourdan/Rainbow-FontView#3]
Opening the colorNames.txt files for writing does not work if the `info` folder does not exist. If the folder does not exist, it must first be created before writing the file.

<img width="652" alt="Bildschirm­foto 2023-02-28 um 13 21 08" src="https://user-images.githubusercontent.com/3776198/221854070-a7f0c3cc-ea64-4e79-b315-e6307ec402d7.png">

Related: https://github.com/schriftgestalt/glyphs-packages/pull/125

**Comment by HugoJourdan** [comment]
Fixed
